version: '2'

services:
  php80:
    build: ./80
    volumes:
      - ../../:/app/monitoring
    working_dir: /app/monitoring
    command: [bash, -c, "composer install && make test"]

#  php81:
#    build: ./81
#    volumes:
#      - ../../:/app/monitoring
#    working_dir: /app/monitoring
#    command: [bash, -c, "composer install && make test"]