version: '2'

services:
  php81:
    build: ./81
    volumes:
      - ../../:/app/monitoring
    working_dir: /app/monitoring

  php80:
    build: ./80
    volumes:
      - ../../:/app/monitoring
    working_dir: /app/monitoring
